services:
  - type: web
    name: stockflow
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn stockflow.wsgi:application --chdir stockflow
    envVars:
      - key: PYTHON_VERSION
        value:  3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: stockflow.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: stockflow-w4e7.onrender.com 